version: "3.3"

services:

    traefik:
        image: "traefik:v2.10"
        container_name: "traefik"
        command:
            #- "--log.level=DEBUG"
            - "--api.insecure=true"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--entrypoints.web.address=:8282"
        ports:
            - "8282:8282"
            - "8080:8080"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"

    test-backend:
        deploy:
            replicas: 1 # Increase on deploy
        build: .
        environment:
#            - "BIN_PATH=src/index.js"
            - "BIN_PATH=node_modules/nodemon/bin/nodemon.js --inspect=0.0.0.0:9229 src/index.js"
        env_file: .env_pokedex
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.test-backend.rule=Host(`pokedex.localhost`)"
            - "traefik.http.routers.test-backend.entrypoints=web"
        expose:
            - "80"
        ports:
            - '9229:9229'
        depends_on:
            -   postgres
        links:
            - postgres
        volumes:
            - "./:/usr/app"
    postgres:
        image: postgres:15.2-alpine
        env_file: .env_postgres
        expose:
            - "5432"
        volumes:
            - db:/var/lib/postgresql/data

volumes:
    db:
        driver: local