version: "3.3"

services:

    traefik:
        image: "traefik:v2.10"
        container_name: "traefik"
        command:
            #- "--log.level=DEBUG"
            - "--api.insecure=true"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--entrypoints.web.address=:8282"
        ports:
            - "8282:8282"
            - "8080:8080"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"

    pokedex:
        deploy:
            replicas: 2
        image: "traefik/whoami"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.pokedex.rule=Host(`pokedex.localhost`)"
            - "traefik.http.routers.pokedex.entrypoints=web"